In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.8.0+cpu


In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
ten = torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
ten

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
ten.ndim

3

In [15]:
ten.shape

torch.Size([1, 3, 3])

In [16]:
ran = torch.rand(3,4)
ran

tensor([[0.5636, 0.3421, 0.6067, 0.9838],
        [0.5468, 0.9465, 0.8579, 0.0712],
        [0.9747, 0.9290, 0.7917, 0.1624]])

In [17]:
torch.rand(3,3)

tensor([[0.2482, 0.0033, 0.9605],
        [0.9402, 0.6839, 0.7878],
        [0.0841, 0.5192, 0.4633]])

In [18]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
one =torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
one.dtype

torch.float32

In [21]:
torch.range(0,10)

C:\Users\dhruv joshi\AppData\Local\Temp\ipykernel_21292\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
one_2_ten = torch.arange(start=1,end=11,step=1)
one_2_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
ten_zero = torch.zeros_like(input = one_2_ten)

In [24]:
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [26]:
a+10

tensor([11, 12, 13])

In [27]:
a*10

tensor([10, 20, 30])

In [28]:
a-10

tensor([-9, -8, -7])

In [29]:
a.mul(10)

tensor([10, 20, 30])

In [30]:
a.add(10)

tensor([11, 12, 13])

In [31]:
a.sub(1)

tensor([0, 1, 2])

In [32]:
torch.mul(a,10)

tensor([10, 20, 30])

In [33]:
torch.add(a,10)

tensor([11, 12, 13])

In [34]:
torch.sub(a,1)

tensor([0, 1, 2])

matrix multi
* (3,2) @ (3,2) not work


* (3,2)@ (2,3) will work

In [35]:
torch.matmul(torch.rand(3,2),torch.rand(3,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x3)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.1406, 0.3400],
        [0.3785, 1.2224]])

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.6344, 0.5289, 1.0487],
        [0.7714, 0.5071, 0.9773],
        [0.8328, 0.5913, 1.1511]])

In [ ]:
# tensor aggregation (max . min , sum , mean etc)

In [40]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(1,9)

In [ ]:
x_reshape,x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z,z.shape

In [ ]:
#changi z changes x
z[:,0] = 5
z,x

NameError: name 'z' is not defined

In [41]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [48]:
# torch.squeeze() - remove all single dimensions from a tensor
# torch.unsqueeze() - add a single dimension to a tensor at a specific dim
x_reshaped = x.reshape(1, 10)




In [49]:
x_reshaped.shape

torch.Size([1, 10])

In [50]:
x_reshaped.squeeze()

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
x_reshaped.squeeze().shape

torch.Size([10])